package com.ibpms.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

/**
 * Embedded within {@link BusinessPolicy}. Describes a document that must
 * (or may optionally) be provided during the process lifecycle (RF-01).
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class DocumentRequirement {

    /** UUID generated by the client or backend at creation time. */
    private String id;

    /** Human-readable name, e.g. "Cédula de identidad". */
    private String name;

    private String description;

    /**
     * MIME types accepted for this document,
     * e.g. {@code ["application/pdf", "image/jpeg"]}.
     */
    private List<String> allowedMimeTypes;

    /** Whether this document must be uploaded for the process to start. */
    private boolean mandatory;

    /**
     * When this document should be uploaded:
     * {@code "PROCESS_START"} or the {@code nodeId} of an ACTION node.
     */
    private String uploadStage;

    /**
     * Who may upload this document:
     * {@code "CLIENT"}, {@code "EMPLOYEE"} or {@code "ANY"}.
     */
    private String uploaderRole;

    /** Maximum allowed file size in bytes (null = unlimited). */
    private Long maxSizeBytes;
}
