spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI}

spring.application.name=PoliticaNegocio

server.port=${PORT:8080}

logging.level.org.springframework.data.mongodb=DEBUG
